site_name: FlatBuffers Docs
site_url: https://dbaileychess.github.io/flatbuffers-mkdocs/
theme:
  name: material
  logo: assets/flatbuffers_logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # Allows content tabs to link together
    - content.tabs.link

    # Expand nav folders by default
    - navigation.expand

    # Allows code block annotations
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets:
      # Allows direct embedded of remote files
      url_download: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - Overview: "index.md"
  - Tutorial: "tutorial.md"
  - Building: "building.md"
  - Schema: "schema.md"
  - Grammar: "grammar.md"
